DROP SEQUENCE bid_counter;
CREATE SEQUENCE bid_counter START WITH 0 INCREMENT BY 1 MINVALUE 0 NOCYCLE;

DROP SEQUENCE hid_counter;
CREATE SEQUENCE hid_counter START WITH 0 INCREMENT BY 1 MINVALUE 0 NOCYCLE;

DROP SEQUENCE borid_counter;
CREATE SEQUENCE borid_counter START WITH 0 INCREMENT BY 1 MINVALUE 0 NOCYCLE;

DROP SEQUENCE fid_counter;
CREATE SEQUENCE fid_counter START WITH 0 INCREMENT BY 1 MINVALUE 0 NOCYCLE;